### ISSUE TITLE
Corrupt SVO from Multi-Camera Encoding

### ISSUE THREAD

**Issue by mepix** [stereolabs/zed-multi-input#2]
I'm trying to extend this example code to save a SVO file for each connected ZED camera (SDK 2.4.1).  With my basic modifications (overview below), the program will run and display the camera frames in a window as expected.  A SVO file is produced for each camera in the specified location, however I cannot open the produced SVO files with _ZED Explorer_ or any of the example SVO scripts included in '/usr/local/zed/sample/svo recording/'.

### Enable Recording
After line 99, I've included:
``` cpp
std::string recordFileName = "/path/to/file/" + std::to_string(zedSerialNumber) + ".svo";
zed[i]->enableRecording(
                    (sl::String)(recordFileName.c_str()),
                    sl::SVO_COMPRESSION_MODE_LOSSY);
```

### Thread Task Function
``` cpp
void grab_run(int x) {
    sl::Mat aux;
    sl::RuntimeParameters rt_params;
    while (!stop_signal) {
        sl::ERROR_CODE res = zed[x]->grab(rt_params);

        if (res == sl::SUCCESS) {
            ZED_Timestamp[x] = zed[x]->getCameraTimestamp();
            zed[x]->retrieveImage(aux, sl::VIEW_LEFT, sl::MEM_CPU);
            cv::Mat(aux.getHeight(), aux.getWidth(), CV_8UC4, aux.getPtr<sl::uchar1>(sl::MEM_CPU)).copyTo(SbSResult[x](cv::Rect(0, 0, width, height)));
            zed[x]->retrieveImage(aux, sl::VIEW_DEPTH, sl::MEM_CPU);
            cv::Mat(aux.getHeight(), aux.getWidth(), CV_8UC4, aux.getPtr<sl::uchar1>(sl::MEM_CPU)).copyTo(SbSResult[x](cv::Rect(width, 0, width, height)));
            sl::RecordingState recState = zed[x]->record();
            if(!recState.status){
                std::cout << "Error Writing to SVO File: " << x << std::endl;
            }

        }
        sl::sleep_ms(1);
    }
    zed[x]->disableRecording();
    zed[x]->close();
    delete zed[x];
}
```
### Runtime
Occasionally, I will see an error like this at the termination of the program, but I haven't been able to tell if this is from the SVO recording or updating the GUI windows with the frames.
```
in sl::ERROR_CODE sl::Mat::updateGPUfromCPU() : cuda error [29]: driver shutting down.
in sl::ERROR_CODE sl::Mat::updateGPUfromCPU() : cuda error [29]: driver shutting down.
```
Otherwise, the code executes cleanly.

### Corrupt SVO Files
The produced SVO files cannot be opened by any of the methods provided in the SDK.  There is no warning nor error message, the applications and scripts freeze and hang.  I can generate and playback other SVO files, just not the ones created by the multi-threaded code.

Is the SVO recording feature in the SDK thread safe?  What am I missing here?  What else could be corrupting the SVO file?

**Comment by sneheshs** [comment]
Hi,

I did a slightly different modification and it works well with mine. However, it works for two cameras, but on the third camera for some reason, I am getting a "failed to create encoder : NvEncoderCuda" error and is not able to record. All three cameras are connected to USB 3.1 and I am recording at 720p at 30 fps. Any help is appreciated!

Thinking it could be CUDA issue (based on the error message) during compression, I tried non-compression mode SVO_COMPRESSION_MODE_LOSSLESS mode instead of my desired SVO_COMPRESSION_MODE_AVCHD, and the problem is gone. However, I need the compression otherwise the storage will be huge. Please advise if there is a patch/ fix for this issue?

Please help address the following issue:
` failed to create encoder : NvEncoderCuda : Encoder Initialization failed at /home/gitlab-runner/builds/08da6f5e/0/sl/ZEDKit/lib/src/sl_input/NVCompression/NvCodec/NvEncoder/NvEncoderCuda.cpp:36`


```
snehesh@snehesh:~/PROJECTS/zed/zed-multi-camera/build$ ./ZED_Multi_Camera 
 Number of ZED Detected : 3
ZED n°0 SN 19649 -> Result: SUCCESS
ZED n°1 SN 23326 -> Result: SUCCESS
ZED n°2 SN 21379 -> Result: SUCCESS
SVO is Recording, use Ctrl-C to stop.
 failed to create encoder : NvEncoderCuda : Encoder Initialization failed at /home/gitlab-runner/builds/08da6f5e/0/sl/ZEDKit/lib/src/sl_input/NVCompression/NvCodec/NvEncoder/NvEncoderCuda.cpp:36

^Csnehesh@snehesh:~/PROJECTS/zed/zed-multi-camera/build$ ll
total 6048
drwxrwxr-x 3 snehesh snehesh    4096 Aug 26 16:39 ./
drwxrwxr-x 6 snehesh snehesh    4096 Aug 26 10:02 ../
-rw-rw-r-- 1 snehesh snehesh   20148 Aug 26 10:00 CMakeCache.txt
drwxrwxr-x 5 snehesh snehesh    4096 Aug 26 16:39 CMakeFiles/
-rw-rw-r-- 1 snehesh snehesh    1403 Aug 26 10:00 cmake_install.cmake
-rw-rw-r-- 1 snehesh snehesh    4863 Aug 26 15:40 Makefile
-rw-rw-r-- 1 snehesh snehesh 2860511 Aug 26 16:44 test_0.svo
-rw-rw-r-- 1 snehesh snehesh 2805616 Aug 26 16:44 test_1.svo
-rw-rw-r-- 1 snehesh snehesh       0 Aug 26 16:44 test_2.svo
-rwxrwxr-x 1 snehesh snehesh  478224 Aug 26 16:39 ZED_Multi_Camera*
snehesh@snehesh:~/PROJECTS/zed/zed-multi-camera/build$ 
```

**Comment by obraun-sl** [comment]
Hi,
There is a limitation of 2 encoders (2 recordings) when using desktop GPUs.
Only NVIDIA Quadro and Jetson platform can support more than 2 encoder running on the same time.

See here : 
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix#Encoder
in the Max # of concurrent sessions column.

**Comment by kushal2507** [comment]
@mepix I'm having the same problem with my .svo files. Cannot open them with any of the listed methods, but all other files are opening perfectly. Were you able to resolve the issue by any chance?

**Comment by obraun-sl** [comment]
@kushal2507 Best is to open a new issue with the description of your problem.
Make sure you mention the OS, the SDK version and the camera model.
Thanks.

**Comment by mepix** [comment]
@kushal2507 Sorry, no. I was under time constraints and ended up punting by using an OpenCV based camera class I already had working with other cameras instead of the ZED SDK. I have not looked at this issue since Jetpack 3 & ZED SDK 2.4.1. For all I know, I could have been missing something obvious, or there could have been some rework to the SDK in the past year+.

**Comment by cdforigua05** [comment]
Hi, 
I am struggling with the same problem of corrupt svo files. @sneheshs would you please share what did you change on the multi-camera code? 
Thanks !!

**Comment by Myzhar** [comment]
@cdforigua05 this is a closed issue, please open a new one describing you problem in detail.
You can cite this issue regarding features in common, but please never reply to a closed issue
