### ISSUE TITLE
Concatenating multiple sl::mat images

### ISSUE THREAD

**Issue by kushal2507** [stereolabs/zed-multi-input#6]
Is there a method to concatenate 2 or more sl::mat images? Something similar to cv::hconcat or cv::vconcat?? 

I dont want to convert my images to cv::Mat images and want to record images from 2 or more cameras simultaneously in a single window.

**Comment by Rutherfordum** [comment]
I'm also wondering if it's possible to use 3 cameras at the same time and stitch a 360 picture?
