### ISSUE TITLE
xMemory acces violation

### ISSUE THREAD

**Issue by LudoTexx** [stereolabs/zed-multi-input#7]
Hello,

Our compagny have now 3 ZED2 cameras, i have tried to run the pulticam sample just for a first test, but he didn't compil and run.

Did you know what the problem is? I have try on 3 differents computers.

![2020-04-20 (1)](https://user-images.githubusercontent.com/19667047/79735996-6fa87500-82f9-11ea-9267-205f51e7664f.png)

Thank you in advance.

Regard's

**Comment by obraun-sl** [comment]
Hi,

This is because the ZED libraries are built in Release mode, and your program is built in Debug mode.
Use ReleaseWithDebugInfos built mode to do step by step debugging with ZED SDK.

**Comment by LudoTexx** [comment]
F*** can't believe that...... i'm feel bad about that mistake !!

Sorry for that and thak you.
