### ISSUE TITLE
Exception acces violation.

### ISSUE THREAD

**Issue by LudoTexx** [stereolabs/zed-multi-input#8]
Hello, 

i have modified the multi-camera sample project for adding streaming option and remove preview windows. That work well for like 3/4 hours after that i get an acces violation exception, without any kind of informations about the problem.

![Annotation 2020-04-23 145944](https://user-images.githubusercontent.com/19667047/80183867-e7341800-8609-11ea-9c24-8413f74a14e5.png)

Did you have any idea about the problem?

Thanks in advance.

(EDIT) Running in Release

**Comment by LudoTexx** [comment]
Update statut: 

Still try to stream 4 ZED cameras to local network. @1080-30 fps.

I have now 3 "ZED 2" camera, connected to a PciE card usb 3.0.

I have the still the same error, but that work like 10/20 seconds.

I have an GTX1660 oc edition, I5-9600K and 8 go of RAM.

When my program stop, a hear the noise like when usb is disconnected, did you think is a problem about power supply, GPU card or any idea?

Thank you in advance.


EDIT : i have run my program with 3 cams, resolution VGA, my program run... (10 min now), but on client i found only 2 zed cam with : 

Camera::getStreamingDeviceList().size(); 


EDIT 2 ;

![Annotation 2020-04-24 183453](https://user-images.githubusercontent.com/19667047/80236065-e677a200-865a-11ea-8ace-73070ac095d0.png)

**Comment by obraun-sl** [comment]
Can you run your program in ReleaseWithDebugInfos? It might give more insight about the program stop behavior.

**Comment by LudoTexx** [comment]
Hello and thank you for taking time to help me.

My program run for some seconds and then crash.


Here a screenshot :  I dont see any difference in ReleaseWithDebugInfos

![Annotation 2020-04-27 100123](https://user-images.githubusercontent.com/19667047/80350723-72631700-8871-11ea-8de7-dfb8e5bf504c.png)


Here my test code : 



`#include <stdio.h>
#include <string.h>
#include <thread>

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include <sl/Camera.hpp>
using namespace sl;

using namespace std;

const int MAX_ZED = 12;

sl::Camera* zed[MAX_ZED];
cv::Mat SbSResult[MAX_ZED];
cv::Mat ZED_LRes[MAX_ZED];
int width, height;
sl::Timestamp ZED_Timestamp[MAX_ZED];

bool stop_signal;


void grab_run(int x) {
    sl::Mat aux;
    sl::RuntimeParameters rt_params;
    while (!stop_signal) 
    {
        sl::ERROR_CODE res = zed[x]->grab(rt_params);
        sl::sleep_ms(1);
    }
    zed[x]->close();
    delete zed[x];
}

int main(int argc, char** argv) {

    sl::InitParameters params;
    params.depth_mode = sl::DEPTH_MODE::PERFORMANCE;
    params.camera_resolution = sl::RESOLUTION::HD1080;
    params.camera_fps = 30;

    StreamingParameters stream_params;
    stream_params.codec = STREAMING_CODEC::H264;
    stream_params.bitrate = 12500;
    stream_params.port = 30000;

    StreamingParameters stream_params1;
    stream_params1.codec = STREAMING_CODEC::H264;
    stream_params1.bitrate = 12500;
    stream_params1.port = 31000;

    StreamingParameters stream_params2;
    stream_params2.codec = STREAMING_CODEC::H264;
    stream_params2.bitrate = 12500;
    stream_params2.port = 32000;

    std::vector<sl::DeviceProperties> devList = sl::Camera::getDeviceList();
    int nb_detected_zed = devList.size();


    std::cout << " Number of ZED Detected : " << nb_detected_zed << std::endl;
    // Create every ZED and init them
    for (int i = 0; i < nb_detected_zed; i++) {
        zed[i] = new sl::Camera();
        params.input.setFromCameraID(i);

        sl::ERROR_CODE err = zed[i]->open(params);



        if (err != sl::ERROR_CODE::SUCCESS) {
            cout << "ZED no. " << i << " -> Result: " << sl::toString(err) << endl;
            delete zed[i];
            return 1;
        }
        else
            cout << "ZED no. " << i << " sn :" << zed[i]->getCameraInformation().serial_number << " -> Result: " << sl::toString(err) << endl;

        //

       /** width = zed[i]->getCameraInformation().camera_resolution.width;
         height = zed[i]->getCameraInformation().camera_resolution.height;
         SbSResult[i] = cv::Mat(height, width * 2, CV_8UC4, 1);*/
    }

    char key = ' ';

    zed[0]->enableStreaming(stream_params);
    zed[1]->enableStreaming(stream_params1);
    zed[2]->enableStreaming(stream_params2);

    // Create each grab thread with camera id as parameter
    std::vector<std::thread*> thread_vec;
    for (int i = 0; i < nb_detected_zed; i++)
    {
        thread_vec.push_back(new std::thread(grab_run, i));
    }

    // Loop until 'q' is pressed
    while (key != 'q') {

        cout << "..... \n";
        key = cv::waitKey(20);

        // Send stop signal to end threads
        //stop_signal = true;
    }

        // Wait for every thread to be stopped
        for (auto it : thread_vec) it->join();

        return 0;
    }

`

**Comment by LudoTexx** [comment]
Please any help ??

NvEncoderCuda error

![Annotation 2020-04-30 122357](https://user-images.githubusercontent.com/19667047/80700550-31bc0580-8ade-11ea-9f33-f8297ea4d29e.png)

**Comment by obraun-sl** [comment]
Hi,
If you are not using a Quadro NVIDIA card (or a jetson), the number of encoder is limited by NVIDIA to 2 session. 
Therefore you cannot enable 3 streaming in the same time, unless you switch to Quadro cards which have unlimited encoder.

**Comment by LudoTexx** [comment]
Hi and thanks for your answer, that i was thinking and that why i have told in my second post i try to stream 4 Zed with an GTX1660.

 But ok not a problem, i will order a Quadro now, but did i need a Quadro too on receiver side?

**Comment by obraun-sl** [comment]
No On the receiver side (decoding), there is no limitations on nvidia cards.

**Comment by LudoTexx** [comment]
Ok, so i have order an NVIDIA Quadro  and 1000W supply too. because actually we have an 650W power supply and i have think that will be not enough for 4 ZED2 camera and 5 GPIO cards.

Thank you very much.

**Comment by LudoTexx** [comment]
So, i have make order to the shop service and i can receive fast an Quadro P4000, is that ok?

**Comment by LudoTexx** [comment]
Sorry, but please could you confirm me a Quadro P4000 is okey for 4 cameras streaming? Thank you

**Comment by obraun-sl** [comment]
Yes that should be enough for 4 camera streaming.

**Comment by LudoTexx** [comment]
Thank you very much.
