### ISSUE TITLE
Multi camera - access violation...

### ISSUE THREAD

**Issue by LudoTexx** [stereolabs/zed-multi-input#9]
hello,

So, i have buy a Quadro P4000, i have buy  a Corsair 1000W power supply and PCIe USB3.0 card and i got the same error...again

I run my program and sometimes he crash after 2h, sometimes after 2 min, or 10 seconde.. same on stream and local display.

I dont understand.. i hear the same signal like USB is disconnected from computer, immediatly the sound like usb is reconnected and my program crash.

Here the last part of my output ;

```
Le thread 0x5a8 s'est arrêté avec le code 0 (0x0).
'ZED_Multi_Camera.exe' (Win32) : Chargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\nvldumdx.dll'. 
'ZED_Multi_Camera.exe' (Win32) : Chargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\nvd3dumx.dll'. 
Le thread 0x690 s'est arrêté avec le code 0 (0x0).
'ZED_Multi_Camera.exe' (Win32) : Chargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\NvCamera\NvCameraWhitelisting64.dll'. 
'ZED_Multi_Camera.exe' (Win32) : Déchargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\NvCamera\NvCameraWhitelisting64.dll'
'ZED_Multi_Camera.exe' (Win32) : Déchargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\nvd3dumx.dll'
'ZED_Multi_Camera.exe' (Win32) : Déchargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\nvldumdx.dll'
'ZED_Multi_Camera.exe' (Win32) : Chargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\nvldumdx.dll'. 
'ZED_Multi_Camera.exe' (Win32) : Chargé 'C:\Windows\System32\DriverStore\FileRepository\nv_dispwi.inf_amd64_56a64c0d620d34fe\nvd3dumx.dll'. 
Le thread 0x2634 s'est arrêté avec le code 0 (0x0).
Exception levée à 0x00007FF8CD1B3D90 dans ZED_Multi_Camera.exe : 0xC0000005 : Violation d'accès lors de l'exécution à l'emplacement 0x00007FF8CD1B3D90.
```

And here my test code ;

```
#include <stdio.h>
#include <string.h>
#include <thread>

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include <sl/Camera.hpp>
using namespace sl;

using namespace std;

const int MAX_ZED = 12;

sl::Camera* zed[MAX_ZED];
cv::Mat SbSResult[MAX_ZED];
cv::Mat ZED_LRes[MAX_ZED];
int width, height;
sl::Timestamp ZED_Timestamp[MAX_ZED];

bool stop_signal;


void grab_run(int x) {
    sl::Mat aux;
    sl::RuntimeParameters rt_params;
    while (!stop_signal) 
    {
        sl::ERROR_CODE res = zed[x]->grab(rt_params);
        sl::sleep_ms(1);
    }
    zed[x]->close();
    delete zed[x];
}

int main(int argc, char** argv) {

    sl::InitParameters params;
    params.depth_mode = sl::DEPTH_MODE::NONE;
    params.camera_resolution = sl::RESOLUTION::HD1080;
    params.camera_fps = 30;

    StreamingParameters stream_params;
    stream_params.codec = STREAMING_CODEC::H264;
    stream_params.bitrate = 12500;
    stream_params.port = 30000;

    StreamingParameters stream_params1;
    stream_params1.codec = STREAMING_CODEC::H264;
    stream_params1.bitrate = 12500;
    stream_params1.port = 30002;

    StreamingParameters stream_params2;
    stream_params2.codec = STREAMING_CODEC::H264;
    stream_params2.bitrate = 12500;
    stream_params2.port = 30004;

    std::vector<sl::DeviceProperties> devList = sl::Camera::getDeviceList();
    int nb_detected_zed = devList.size();


    std::cout << " Number of ZED Detected : " << nb_detected_zed << std::endl;
    // Create every ZED and init them
    for (int i = 0; i < nb_detected_zed; i++) {
        zed[i] = new sl::Camera();
        params.input.setFromCameraID(i);

        sl::ERROR_CODE err = zed[i]->open(params);



        if (err != sl::ERROR_CODE::SUCCESS) {
            cout << "ZED no. " << i << " -> Result: " << sl::toString(err) << endl;
            delete zed[i];
            return 1;
        }
        else
            cout << "ZED no. " << i << " sn :" << zed[i]->getCameraInformation().serial_number << " -> Result: " << sl::toString(err) << endl;

        //

        width = zed[i]->getCameraInformation().camera_resolution.width;
         height = zed[i]->getCameraInformation().camera_resolution.height;
         SbSResult[i] = cv::Mat(height, width * 2, CV_8UC4, 1);
    }

    char key = ' ';

    zed[0]->enableStreaming(stream_params);
    zed[1]->enableStreaming(stream_params1);
    zed[2]->enableStreaming(stream_params2);

    // Create each grab thread with camera id as parameter
    std::vector<std::thread*> thread_vec;
    for (int i = 0; i < nb_detected_zed; i++)
    {
        thread_vec.push_back(new std::thread(grab_run, i));
    }

    // Loop until 'q' is pressed
    while (key != 'q') {

        cout << "streaming..... \n";
        key = cv::waitKey(20);

        // Send stop signal to end threads
        //stop_signal = true;
    }

        // Wait for every thread to be stopped
        for (auto it : thread_vec) it->join();

        return 0;
    }

```

On very start of this video, this is the song i'm talking about : 

https://www.youtube.com/watch?v=YgZZNFjwSJ0

Error is the same with this program without any modifications : 
https://github.com/stereolabs/zed-multi-camera

Please i really need help

**Comment by LudoTexx** [comment]
Bump.. any idea please? Because we need one more camera but if that doesn't work with 3, i'm pretty sure that will not work with 4

**Comment by obraun-sl** [comment]
This seems to be a USB connection issue. Maybe the PCI usb card cannot handle 3 cameras. 
To spread the USB input more efficiently,it will be better to have 2 cameras connected on the USB3.0 motherboard port and 1/2 cameras connected on the PCI USB card.

**Comment by LudoTexx** [comment]
Hello and thanks for your answer, i have try what you say its the same. i got this message now : 

![Annotation 2020-05-21 173220](https://user-images.githubusercontent.com/19667047/82576169-c4097380-9b89-11ea-94df-d4b14aec9276.png)

**Comment by obraun-sl** [comment]
The third camera cannot be openned due to low USB bandwidth( it can open the camera but not grab images from it). 
Maybe try with 
    params.camera_resolution = sl::RESOLUTION::HD1080;
    params.camera_fps = 15;
to reduce the overall bandwidth

**Comment by LudoTexx** [comment]
Thank you,

our need is 4 camera at minimum 30 fps 1080p.

So if it's not possible we need to look for another product.

But this is not what is writing here :

https://github.com/stereolabs/zed-multi-camera#limitations

We have buy everything for getting the perfect configuration, not cheap products, and that not working.. this is not cool.....

**Comment by adujardin** [comment]
You may need more than 1 PCI USB card for 4 ZED at full speed considering the required bandwidth. 

Most of the PCI cards have only 1 controller shared between ports, meaning you can basically only plug 1 ZED on it. Some have 1 controller per port (like [this one](https://www.sonnettech.com/product/legacyproducts/allegroprousb3pcie.html), maybe [this one too](https://www.amazon.com/StarTech-com-Express-SuperSpeed-Dedicated-Channels/dp/B00HJZEA2S) but we didn't test it) which could handle the bandwidth.

The controllers are usually visible on the boards.

**Comment by PrivHateVoid** [comment]
We already have 2 controllers for 4 port (10Gb/s) , one ZED cam on each and one on motherboard USB 3.0.

**Comment by LudoTexx** [comment]
We already have a starteck 4 usb with 2 dedicated supply (10gb/s), one zed on each supply and one on mother board.

**Comment by LudoTexx** [comment]
Can you tell me how many ZED can stream a jetson NANO or TX2 or XAVIER in 1080P at 30 fps FOR SURE.

**Comment by LudoTexx** [comment]
Well, without solution we have ordered 4 jetson nano.

We use zed camera streaming in python. 

-Open box
- Flash SD card
- Install and update python, zed sdk, etc..
- Write your script
- Run the script

I have do that in.. well... 2.5 hours the first time.. after loosing 2 month to try in c++ on windows.
